import Foundation
import SwiftData

@Model
final class Flashcard {
    @Attribute(.unique) var id: UUID
    var capturedAt: Date
    // Stored as String so SwiftData #Predicate can build a key path on it.
    // Use the `state` computed property everywhere else in the app.
    var stateRawValue: String

    // Raw scan — stored as JPEG Data, nil until camera captures.
    // externalStorage tells SwiftData to keep the blob as a file reference rather
    // than inline in the model store, preventing 5–15 MB per pending card from
    // being loaded into memory when fetching a deck's flashcards.
    @Attribute(.externalStorage) var rawPhotoData: Data?

    // Downscaled thumbnail (200 pt wide) generated by AIEngine just before
    // rawPhotoData is cleared. Used for card previews after AI extraction.
    var thumbnailData: Data?

    // AI-extracted fields — nil until processing completes
    var question: String?
    var answer: String?
    var explanation: String?
    var difficulty: Int?           // 1 (easy) → 5 (hard)

    // Study stats
    var reviewCount: Int
    var correctCount: Int
    var lastReviewedAt: Date?

    // User-assigned tags for filtering and organisation (V2).
    // Defaults to empty — existing cards get [] on migration.
    var tags: [String] = []

    var deck: Deck?

    /// Convenience accessor — reads/writes `stateRawValue`.
    var state: ProcessingState {
        get { ProcessingState(rawValue: stateRawValue) ?? .pending }
        set { stateRawValue = newValue.rawValue }
    }

    init(rawPhotoData: Data? = nil) {
        self.id = UUID()
        self.capturedAt = Date()
        self.stateRawValue = ProcessingState.pending.rawValue
        self.rawPhotoData = rawPhotoData
        self.reviewCount = 0
        self.correctCount = 0
    }

    var accuracyRate: Double {
        guard reviewCount > 0 else { return 0 }
        return Double(correctCount) / Double(reviewCount)
    }
}
