import UIKit

// UIKit-specific conveniences for Flashcard — kept separate so the @Model class
// does not import UIKit (UIKit types are not SwiftData-storable and importing it
// in a model file can confuse the Swift compiler's isolation analysis).
extension Flashcard {
    /// Full-resolution scan image. Only non-nil while the card is still pending
    /// (before AIEngine clears rawPhotoData after extraction).
    var sourceImage: UIImage? {
        guard let data = rawPhotoData else { return nil }
        return UIImage(data: data)
    }

    /// 200 pt thumbnail generated by AIEngine just before rawPhotoData is cleared.
    /// Use this in card lists and previews — it's always available for active cards.
    var thumbnailImage: UIImage? {
        if let data = thumbnailData { return UIImage(data: data) }
        return sourceImage   // fallback while card is still pending
    }
}

// MARK: - UIImage scaling helper

extension UIImage {
    /// Returns a copy scaled down to `maxWidth` points, maintaining aspect ratio.
    /// If the image is already narrower than `maxWidth`, returns `self` unchanged.
    func scaledDown(toWidth maxWidth: CGFloat) -> UIImage {
        guard size.width > maxWidth else { return self }
        let scale = maxWidth / size.width
        let newSize = CGSize(width: maxWidth, height: size.height * scale)
        let renderer = UIGraphicsImageRenderer(size: newSize)
        return renderer.image { _ in draw(in: CGRect(origin: .zero, size: newSize)) }
    }
}
